### ISSUE TITLE
启动成功，随后就停了，不会发送库存信息

### ISSUE THREAD

**Issue by nie365** [pzure/hax-woiden-monitor#2]
启动成功，随后就停了，不会发送库存信息，错误代码
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "hax-woiden.py", line 73, in checkHax
    if len(dc) != 0:
TypeError: object of type 'NoneType' has no len()
```
还有配置信息中不需要添加chat_id吗?不添加就不会收到消息，我加上了chat_id后才能收到。

**Comment by pzure** [comment]
需要添加chat_id ，指定用户发送
